version: '3'
services:
  jupyter-server:
    image: wsc_port
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./notebooks/:/code/notebooks/"
    ports:
      - "8888:8888"
    command: bash -c "jupyter lab --allow-root --ip=0.0.0.0 --port=8888 --no-browser"
  train:
    image: wsc_port
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./models/:/code/models/"
    command: bash -c "source activate wsc_port && exec make train"
  generate:
    image: wsc_port
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "source activate wsc_port && exec make generate"
  winograd_test:
    image: wsc_port
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "source activate wsc_port && exec make winograd_test"
